version: "3"
services:
  mongo:
    container_name: express-api_mongocontainer
    image: mongo
    ports:
    - "27018:27017"
  web:
    build: .
    # image: express-api:latest
    ports:
    - "8080:8080"
    environment:
      MONGO_ENV: "mongo"
      MONGO_PORT: "27017"
    links:
      - mongo
    depends_on:
    - mongo
    
